# Assumes that conda, pip and build-essentials are installed
---
name: datadriven
channels:
- conda-forge

# If you update this list, please also update gpu_ocean/requirements.txt
dependencies:
- python=3.7
- matplotlib
- pandas
- requests
- haversine
- netCDF4
- pyprop
- pyproj
- sklearn